### ISSUE TITLE
Gitflow issue

### ISSUE THREAD

**Issue by sleepylee** [prelude618/surveys#1]
Hi David,
Thank you for your submission, and we at Nimblehq appreciate your effort on completing the coding challenge.
My name is Trung and I'll be in charge of giving the feedbacks here. Please feel free to ping me if there is anything misunderstand.

The first thing I noticed is that all of your working progress were pushed at once, they were not separated by the branches, Pull Request regarding their features/chore concerns.

**Comment by prelude618** [comment]
Hello Trung,
Nice to meet you.

You are right, but these codes have only basic functions.
According to your reviews, i will push all changes from this time.
Sorry about that. but i had not enough time for this implementation cause i worked till late recently.

BR,
